

/*
		TABLE SCHEMA
General 2x2 table with Name and Code columns. 
For the purpose of this example, it is populated statically with "Queued" and "Successful" values.
 _______________________
| 	Name	|	Code	|
|___________|___________|
|   Queued	|	  0		|
| Successful|	  1 	|
|___________|___________|

*/

let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCi5NTk4tLk4rzVHSUTJUitWJVgosTS1NTQFyDZRiYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Name = _t, Code = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Name", type text}, {"Code", Int64.Type}})
in
    #"Changed Type"